# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "1.21.6-1.21.7" branch
  release:
    type: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse version and game versions from tag
        id: parse
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Tag: $TAG"
      
          VERSION_NUMBER=$(echo "$TAG" | sed -E 's/^v([^_]+)_for_.*/\1/')
          echo "Parsed version_number: $VERSION_NUMBER"
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> "$GITHUB_ENV"
      
          VERSION_PART=$(echo "$TAG" | sed -n 's/.*_for_//p')
          echo "Version part: $VERSION_PART"
      
          START=$(echo "$VERSION_PART" | cut -d'-' -f1)
          END=$(echo "$VERSION_PART" | cut -d'-' -f2)
      
          echo "Start: $START"
          echo "End: $END"
      
          JSON_ARRAY=$(python3 scripts/generate_versions.py "$START" "$END")
          echo "GAME_VERSIONS=$JSON_ARRAY" >> "$GITHUB_ENV"
          echo "Parsed GAME_VERSIONS: $JSON_ARRAY"
          
      - name: Zip datapack
        run: |
          cd datapack
          zip ancient_artifacts_2_datapack_.zip ../datapack/pack.mcmeta ../datapack/pack.png ../datapack/data

      - name: Zip resourcepack
        run: |
          cd datapack
          zip ancient_artifacts_2_resourcepack_.zip ../resourcepack/pack.mcmeta ../resourcepack/pack.png ../resourcepack/assets
